name: CI/CD hdev_client to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        run: |
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
          echo "[default]" >> $HOME/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> $HOME/.aws/config

      - name: Npm install babel
        run: |
          npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Npm Install
        run: |
          npm install

      - name: Npm Build
        run: |
          npm run build
        env:
          CI: false

      - name: Upload on S3
        run: aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read
